version: "2"
services:
  registry-server:
    image: registry:2
    restart: always
    container_name: registry-server
    networks:
      notary:
      registry:
        aliases:
          - registry.example.local
    ports:
      - 5000:5000
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /opt/auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_HTTP_TLS_CERTIFICATE: /opt/certs/registry.example.local.crt
      REGISTRY_HTTP_TLS_KEY: /opt/certs/registry.example.local.key
      REGISTRY_HTTP_SECRET: BTpFsd82m01jdyg7ubhew78huij%
    volumes:
      - registry_data:/var/lib/registry
      - ./files/certs:/opt/certs
      - ./files/auth:/opt/auth
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    networks:
      mdb:
      sig:
      notary:
        aliases:
          - notary-server.example.local
    ports:
      - "8080"
      - "4443:4443"
    entrypoint: /usr/bin/env sh
    command: -c "./migrations/migrate.sh && notary-server -config=fixtures/server-config.json"
    depends_on:
      - mysql
      - signer
  signer:
    build:
      context: .
      dockerfile: signer.Dockerfile
    networks:
      mdb:
      sig:
        aliases:
          - notarysigner
    entrypoint: /usr/bin/env sh
    command: -c "./migrations/migrate.sh && notary-signer -config=fixtures/signer-config.json"
    depends_on:
      - mysql
  mysql:
    networks:
      - mdb
    volumes:
      - ./notarysql/mysql-initdb.d:/docker-entrypoint-initdb.d
      - notary_data:/var/lib/mysql
    image: mariadb:10.4
    environment:
      - TERM=dumb
      - MYSQL_ALLOW_EMPTY_PASSWORD="true"
    command: mysqld --innodb_file_per_table
volumes:
  notary_data:
    external: false
  registry_data:
    external: false
networks:
  mdb:
    external: false
  sig:
    external: false
  registry:
      external: false
  notary:
    external: false